version: "3.8"

services:
  db:
    container_name: e2e_db_container
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=e2e_pwd
      - POSTGRES_DB=e2e_db

volumes:
  data: {}
